apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: commissions
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: workflow
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: scai
  labels:
    istio-injection: enabled
---
