apiVersion: v1
kind: Secret
metadata:
  name: repo-kyverno
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: kyverno # Repository name for display
  project: default
  url: https://kyverno.github.io/kyverno/
  type: helm
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kyverno-github-io
  namespace: argocd
spec:
  hosts:
    - kyverno.github.io
  location: MESH_EXTERNAL # Indicates it's outside the mesh
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
