apiVersion: v1
kind: Secret
metadata:
  name: repo-argoproj
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: argoproj # Repository name for display
  project: default
  url: https://argoproj.github.io/argo-helm
  type: helm
---
# apiVersion: networking.istio.io/v1alpha3
# kind: ServiceEntry
# metadata:
#   name: argoproj-chart
#   namespace: argocd
# spec:
#   hosts:
#     - argoproj.github.io
#   location: MESH_EXTERNAL # Indicates it's outside the mesh
#   ports:
#     - number: 443
#       name: https
#       protocol: HTTPS
#   resolution: DNS
