apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appproj
  namespace: argocd
spec:
  project: default
  source:
    path: manifests/argocd/appproj
    repoURL: https://github.com/kevin-kho/local-argo
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
