apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # If application is deleted, resource itself is deleted
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
  name: argocd-eng
  namespace: argocd
spec:
  destination:
    namespace: argocd-prod
    name: in-cluster
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 6.9.3
    helm:
      releaseName: argocd
      valuesObject:
        crds:
          install: false
        createClusterRoles: false

        redis-ha:
          enabled: false

        redisSecretInit:
          enabled: true
          podAnnotations:
            sidecar.istio.io/inject: "false"

          params:
            server.insecure: "true"
            dexserver.disable.tls: "true"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
