apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # If application is deleted, resource itself is deleted
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    # targetRevision: 9.5.11
    # targetRevision: 9.5.2
    targetRevision: 9.3.7
    # targetRevision: 9.0.6
    # targetRevision: 8.2.7
    # targetRevision: 7.9.1
    # targetRevision: 6.9.3
    helm:
      releaseName: argocd
      valuesObject:
        redis-ha:
          enabled: false

        redisSecretInit:
          enabled: true
          podAnnotations:
            sidecar.istio.io/inject: "false"

          params:
            server.insecure: "true"
            dexserver.disable.tls: "true"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
