apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: topograph-branch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/topograph
    repoURL: https://github.com/kevin-kho/topograph
    targetRevision: kh-chart-namespace
    helm:
      releaseName: topograph
  destination:
    name: in-cluster
    namespace: topograph
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
