# apiVersion: networking.istio.io/v1beta1
# kind: ServiceEntry
# metadata:
#   name: github
#   namespace: argocd
# spec:
#   exportTo:
#     - .
#   hosts:
#     - github.com
#     - release-assets.githubusercontent.com
#   location: MESH_EXTERNAL
#   ports:
#     - name: https
#       number: 443
#       protocol: HTTPS
#   resolution: DNS
